services:
  users_api:
    build:
      context: ./APIS
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 4GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3001:3000" 
    volumes:
      - ./APIS/users:/usr/userAPI
    networks:
      - dev_network

  orders_api:
    build:
      context: ./APIS
    ports:
      - "3002:3000"  
    volumes:
      - ./APIS/orders:/ord/ordersAPI
    networks:
      - dev_network

  memberships_api:
    build:
      context: ./APIS
    ports:
      - "3003:3000"  
    volumes:
      - ./APIS/memberships:/ord/memberships_api
    networks:
      - dev_network

  products_api:
    build:
      context: ./APIS
    ports:
      - "3004:3000"
    volumes:
      - ./APIS/products:/mem/productsAPI
    networks:
      - dev_network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: deivid@cardenas.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - dev_network

  db_dev:
    image: postgres:latest
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 4GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    container_name: users_db_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./users_data_dev:/var/lib/postgresql/data
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
