services:
  # Servicio para la API de usuarios
  users_api:
    build:
      context: ./APIS
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 4GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3001:3000" 
    volumes:
      - ./APIS/users:/usr/userAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@users_db:5432/users_db  # URL de conexión para la base de datos de users

  # Servicio para la base de datos de usuarios
  users_db:
    image: postgres
    container_name: users_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users_db  # Nombre de la base de datos para users
    ports:
      - "5432:5432"
    volumes:
      - ./users_data:/var/lib/postgresql/data
    networks:
      - dev_network

  # Servicio para la API de órdenes
  orders_api:
    build:
      context: ./APIS
    ports:
      - "3002:3000"  
    volumes:
      - ./APIS/orders:/ord/ordersAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@orders_db:5432/orders_db  # URL de conexión para la base de datos de órdenes

  # Servicio para la base de datos de órdenes
  orders_db:
    image: postgres
    container_name: orders_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: orders_db  # Nombre de la base de datos para órdenes
    ports:
      - "5433:5432"
    volumes:
      - ./orders_data:/var/lib/postgresql/data
    networks:
      - dev_network

  # Servicio para la API de membresías
  memberships_api:
    build:
      context: ./APIS
    ports:
      - "3003:3000"  
    volumes:
      - ./APIS/memberships:/ord/membershipsAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@memberships_db:5432/memberships_db  # URL de conexión para la base de datos de membresías

  # Servicio para la base de datos de membresías
  memberships_db:
    image: postgres
    container_name: memberships_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: memberships_db  # Nombre de la base de datos para membresías
    ports:
      - "5434:5432"
    volumes:
      - ./memberships_data:/var/lib/postgresql/data
    networks:
      - dev_network

  # Servicio para la API de productos
  products_api:
    build:
      context: ./APIS
    ports:
      - "3004:3000"
    volumes:
      - ./APIS/products:/mem/productsAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@products_db:5432/products_db  # URL de conexión para la base de datos de productos

  # Servicio para la base de datos de productos
  products_db:
    image: postgres
    container_name: products_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: products_db  # Nombre de la base de datos para productos
    ports:
      - "5435:5432"
    volumes:
      - ./products_data:/var/lib/postgresql/data
    networks:
      - dev_network

  # Servicio de Nginx
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"  # Exponiendo el puerto 80 para Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users_api
      - orders_api
      - memberships_api
      - products_api
    networks:
      - dev_network

  # Servicio de PgAdmin para la administración de las bases de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: deivid@cardenas.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
