version: '3.8'

services:
  users_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.users
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 2GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3100:3100" 
    volumes:
      - ./APIS/users:/usr/usersAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@users_db:5432/users_db?schema=public
    depends_on:
      - users_db

  users_db:
    image: postgres
    container_name: users_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users_db
    ports:
      - "5100:5432"
    volumes:
      - ./users_data:/var/lib/postgres/data
      - ./users_logs:/var/log/postgresql
      - ./postgres_configs/postgresql.users.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  orders_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.orders
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 2GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3200:3200"  
    volumes:
      - ./APIS/orders:/ord/ordersAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@orders_db:5432/orders_db?schema=public
    depends_on:
      - orders_db

  orders_db:
    image: postgres
    container_name: orders_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: orders_db
    ports:
      - "5200:5432"
    volumes:
      - ./orders_data:/var/lib/postgres/data
      - ./orders_logs:/var/log/postgresql
      - ./postgres_configs/postgresql.orders.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  memberships_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.memberships
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 2GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3300:3300"  
    volumes:
      - ./APIS/memberships:/mem/membershipsAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@memberships_db:5432/memberships_db?schema=public
    depends_on:
      - memberships_db

  memberships_db:
    image: postgres
    container_name: memberships_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: memberships_db
    ports:
      - "5300:5432"
    volumes:
      - ./memberships_data:/var/lib/postgres/data
      - ./memberships_logs:/var/log/postgresql
      - ./postgres_configs/postgresql.memberships.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  products_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.products
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 2GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3400:3400"
    volumes:
      - ./APIS/products:/pro/productsAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@products_db:5432/products_db?schema=public 
    depends_on:
      - products_db

  products_db:
    image: postgres
    container_name: products_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: products_db
    ports:
      - "5400:5432"
    volumes:
      - ./products_data:/var/lib/postgres/data
      - ./products_logs:/var/log/postgresql
      - ./postgres_configs/postgresql.products.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  payments_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile.payments
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 2GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3500:3500"
    volumes:
      - ./APIS/payments:/pay/paymentsAPI
    networks:
      - dev_network
    environment:
      DATABASE_URL: postgres://postgres:12345@payments_db:5432/payments_db?schema=public 
    depends_on:
      - payments_db

  payments_db:
    image: postgres
    container_name: payments_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: payments_db
    ports:
      - "5500:5432"
    volumes:
      - ./payments_data:/var/lib/postgres/data
      - ./payments_logs:/var/log/postgresql
      - ./postgres_configs/postgresql.payments.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users_api
      - orders_api
      - memberships_api
      - products_api
      - payments_api
    networks:
      - dev_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: deivid@cardenas.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
