FROM node:20

RUN apt-get update && apt-get install -y wget nano postgresql postgresql-contrib && rm -rf /var/lib/apt/lists/*

RUN npm cache clean --force

RUN npm install -g npm@8.12.1

RUN mkdir -p /ord/ordersAPI 

WORKDIR /ord/ordersAPI

COPY orders/package*.json ./

RUN npm install

COPY orders/ ./

RUN npx prisma generate

EXPOSE 3200

CMD ["npx", "nodemon", "app.js"]
