FROM node:20

RUN apt-get update && apt-get install -y wget nano postgresql postgresql-contrib && rm -rf /var/lib/apt/lists/*

RUN npm cache clean --force

RUN npm install -g npm@8.12.1

RUN mkdir -p /pro/productsAPI

WORKDIR /pro/productsAPI

COPY products/package*.json ./

RUN npm install

COPY products/ ./

RUN npx prisma generate

EXPOSE 3400

CMD ["npx", "nodemon", "app.js"]
